### ISSUE TITLE
autoRender:true does not fire change:rendered event

### ISSUE THREAD

**Issue by gdibble** [AmpersandJS/ampersand-view#112]
when using `autoRender:true`, the `change:rendered` event is not thrown

verified in ampersand-view v7.2.0 and v7.3.0

---

useful when having a view listener that auto-stops a progress bar like nprogress.
for instance:
```
this.listenTo(view, 'change:rendered', function () {
  //stop progress
});
```

---

when i use `autoRender:true` this event never fires, however if i use a standard ...
```
  render: function () {
    this.renderWithTemplate();
    return true;
  },
```
...the event is fired!

**Comment by hailwood** [comment]
It isn't just that event. If you use autoRender it seems that no events get hooked up at all.

**Comment by cdaringe** [comment]
@hailwood, a fiddle would be helpful.  i've changed the behavior for `rendered` here,  #119.  I don't forsee this being an issue under the proposed implementation.

**Comment by cdaringe** [comment]
i believe that this addressed in the latest 8.x release.  let me know if its still hurtin ya otherwise!

**Comment by gdibble** [comment]
@cdaringe using the listener in the issue description, this is still not working in 8.x

**Comment by cdaringe** [comment]
it's probably firing the event, but if it's rendering during the instantiation cycle, there's no time for other views to setup listeners on it.  e.g., there's no chance for something else to call `yourAutoRenderingView.on('change', ...)`, because by the time `yourAutoRenderingView` is formally instantiated, it has been rendered, and thus the event is lost.   i'm not sure that it's a bug, but definitely a design consideration.  does that sound right to folks?  what are your thoughts?

in making a fiddle, it the chicken-and-egg problem became very apparent:
http://requirebin.com/?gist=9abae7fb677d5160c5a6
